version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8989:80"
        volumes:
            - "./public/:/var/www/html"
    fpm:
        build:
            context: .
            dockerfile: docker/fpm/Dockerfile
        volumes:
            - "./public/:/var/www/html"
    db:
        build:
            context: .
            dockerfile: docker/db/Dockerfile
        volumes:
            - "./docker/db/data:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres