version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8989:80"
        volumes:
            - "./public/:/var/www/html"
        #todo: add container name based on env variable {{APP-NAME}}-nginx
    fpm:
        build:
            context: .
            dockerfile: docker/fpm/Dockerfile
        volumes:
            - "./public/:/var/www/html"